# Copyright (c) 2025 Mohammad Sheraj Discover is licensed under India PSL v1. You can use this software according to the terms and conditions of the India PSL v1. You may obtain a copy of India PSL v1 at: https://github.com/abirusabil123/discover/blob/main/IndiaPSL1 THIS SOFTWARE IS PROVIDED ON AN “AS IS” BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE. See the India PSL v1 for more details.

tunnel: 6a9960c7-1fe2-4565-a583-6a0a3cd16d31
credentials-file: /etc/cloudflared/6a9960c7-1fe2-4565-a583-6a0a3cd16d31.json
no-autoupdate: true

ingress:
  - hostname: backend.discoverall.space
    service: http://app:3000
  - service: http_status:404
